// <auto-generated />
namespace Project.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class gdgdhg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gdgdhg));
        
        string IMigrationMetadata.Id
        {
            get { return "201702261551479_gdgdhg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
